use example_event_loop::{run, Error};

fn main() -> Result<(), Error> {
    run()
}
