use example_event_loop_console::{run, Error};

fn main() -> Result<(), Error> {
    run()
}
